package model;

public enum Cities {
    LONDON, PARIS, NEW_YORK, TOKYO, DUBAI, ISTANBUL, SINGAPORE, KUALA_LUMPUR, SEOUL, HONG_KONG, BAKU, BANGKOK,
    LOS_ANGELES, BARCELONA, ROME, MILAN, MADRID, BERLIN, MUNICH, FRANKFURT, AMSTERDAM, VIENNA, ZURICH, GENEVA,
    BRUSSELS, COPENHAGEN, STOCKHOLM, OSLO, HELSINKI, WARSAW, PRAGUE, BUDAPEST, ATHENS, LISBON, MOSCOW, SAINT_PETERSBURG,
    KIEV, MINSK, RIGA, TALLINN, VILNIUS, SOFIA, BUCHAREST, BELGRADE, ZAGREB, SARAJEVO, SKOPJE, TIRANA, PRISTINA, PODGORICA,
    CHISINAU, TBILISI, YEREVAN, ASTANA, ALMATY, TASHKENT, ASHGABAT, BISHKEK, DUSHANBE, KHUJAND, ANKARA, TEHRAN, BAGHDAD,
    DAMASCUS, BEIRUT, JERUSALEM, AMMAN, CAIRO, TRIPOLI, TUNIS, ALGIERS, RABAT, CASABLANCA, DAKAR, BAMAKO, OUAGADOUGOU,
    SAINT_EUSTATIUS, SAINT_BARTELEMY, SAINT, SAINT_HELENA, SAINT_PETER;


    public static Cities fromString(String name) {
        try {
            return Cities.valueOf(name.trim().replace(" ", "_").toUpperCase());
        } catch (IllegalArgumentException e) {
            System.err.println("Invalid city name: " + name);
            return null;
        }
    }
}
